name 'apachevhosts'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures apachevhosts'
long_description 'Installs/Configures apachevhosts'
version '0.1.0'
